POST http://localhost:3000/registration 
content-type: application/json

{
    "name":"Nikita",
    "email": "nkutovoy@sfedu.ru",
    "password": "ElizabethNN",
    "surname": "Kutovoy",
    "phone": "+79286187502"
}

###

GET http://localhost:3000 

###

POST http://192.168.43.124:3000/login 
content-type: application/json

{
    "email": "nkutovoy@sfedu.ru",
    "password": "ElizabethNN"
}

###

POST http://192.168.43.124:3000/login 
content-type: application/json

{
    "email": "pupa@gmail.com",
    "password": "pupazalupu"
}

###

POST http://localhost:3000/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmt1dG92b3lAc2ZlZHUucnUiLCJpZCI6MiwiaXNBZG1pbiI6MCwiaWF0IjoxNjIyMjQ1NzI5fQ.SEPZ2Ki8B9ELUZPeme7fsH5Lrl54UC_QVKipzGU9Nsg"
}

###

GET http://localhost:3000/test 
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmt1dG92b3lAc2ZlZHUucnUiLCJpZCI6MiwiaXNBZG1pbiI6MCwiaWF0IjoxNjIyMjQ2NjgxLCJleHAiOjE2MjIyNDc1ODF9.hF8MuvJN6HQJD9Jl3viMO3fiooaUGWRq0gjphSzSwmo

###

POST http://localhost:3000/admin/event/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmt1dG92b3lAc2ZlZHUucnUiLCJpZCI6MiwiaXNBZG1pbiI6MSwiaWF0IjoxNjIyMjUzOTY3LCJleHAiOjE2MjIyNTQ4Njd9.j4d19P1yw2aNMdCsy-5tK0cEYxFk1s-jm6FdHufSTlA

{
    "name":"cyber-waffles-hackathon",
    "description":"yeah boy",
    "address":"chill streat",
    "datetime":"2021-05-30 21:00:00.000",
    "place":{
        "x":"47.22",
        "y":"38.70"
    }
}

###

PUT http://localhost:3000/admin/event
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmt1dG92b3lAc2ZlZHUucnUiLCJpZCI6MiwiaXNBZG1pbiI6MSwiaWF0IjoxNjIyMjU3Mjg3LCJleHAiOjE2MjIyNTgxODd9.FYOhL4bNLfd1ryk947QRiaOOmhFWJeHc-grmEKc4NBo
Content-Type: application/json

{
    "id":2,
    "description":"cyber-waffles-hackathon"
}

###

DELETE http://localhost:3000/admin/event
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibmt1dG92b3lAc2ZlZHUucnUiLCJpZCI6MiwiaXNBZG1pbiI6MSwiaWF0IjoxNjIyMjU3Mjg3LCJleHAiOjE2MjIyNTgxODd9.FYOhL4bNLfd1ryk947QRiaOOmhFWJeHc-grmEKc4NBo
Content-Type: application/json

{
    "id":1
}

###

GET http://localhost:3000/events/near
Content-Type: application/json

###

POST http://localhost:3000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicHVwYUBnbWFpbC5jb20iLCJpZCI6NCwiaXNBZG1pbiI6MCwiaWF0IjoxNjIyMjYyNjU2LCJleHAiOjE2MjIyNjM1NTZ9.oBxv0Wb9zCnRVO0iCLNKdi1mT9rmX36zvakV-EmMvjs

###

POST http://192.168.43.143:3000/passport
authorization: Be eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicHVwYUBnbWFpbC5jb20iLCJpZCI6NCwiaXNBZG1pbiI6MCwiaWF0IjoxNjIyMjYzMzM5LCJleHAiOjE2MjIyNjQyMzl9.ko11LQcpPMGjnyRqNqYAgJefRy0zFeoWVAYXspRK2tc

{
    "buytime":"2021-05-29 00:00:22",
    "firstname":"Ruslan",
    "secondname":"Kutukov",
    "isvip":"true",
    "iguest":"true",
}