POST http://localhost:3000/registratiron 
content-type: application/json

{
    "name":"Nikita",
    "email": "nkutovoy@sfedu.ru",
    "password": "ElizabethNN",
    "surname": "Kutovoy",
    "phone": "+79286187502"
}
###
GET http://localhost:3000 
###
GET http://localhost:3000/getpasswordhash
###
GET http://localhost:3000/getevents
###
GET http://localhost:3000/getpassports


